ALL_WORDS = [
    "odam bor",
    # "bor",
    # "odam",
    "ketaman",
    "pochta bot",
    "pocta bot",
    "po'chta bot",
    "po'cta bot",
    "siro'chni",
    "siro'chniy",
    "sirocniy",
    "sirocni",
    "sirocni",
    "srochniy",
    "sro'chniy",
    "sro'chni",
    "Aloqa",
    "srochni",
    "ta odam bor",
    "bormoqchi",
    "bormoqci",
    "yangi buyurtma",
    "yangi buyurtma.",
    "yo'lovchi",
    "yo'lovci",
    "yolovchi",
    "yolovci",
    "Xabar",
    "xabar",
    "одам бор",
    # "одам",
    # "бор",
    "кетаман",
    "почта бот",
    "поcта бот",
    "пўчта бот",
    "пўcта бот",
    "сирўчни",
    "сирўчний",
    "сироcний",
    "сироcни",
    "сироcни",
    "суроcни",
    "taxi bormi",
    "bormi",
    "тахи борми",
    "борми",
    "почта бор",
    "pochta bor",
    "pocta bor",
    "срочний",
    "срўчний",
    "срўчни",
    "срочни",
    "та одам бор",
    "бормоқчи",
    "бормоқcи",
    "янги буюртма",
    "янги буюртма.",
    "йўловчи",
    "йўловcи",
    "ёловчи",
    "ёловcи",
    "мошина борми",
    "Хабар",
    "moshina bormi",
    "хабар",
    "📧 Xabar:",
    "Жалакудук дан одам бор",
    "Булок боши дан одам бор",
    "Тошкентга мошина борми",
    "Тошкентдан булок боши га одам бор",
    "Тошкентдан ширмонбулокга одам бор",
    "Срочный га мошина керак",
    "Тошкентдан жалакудук га битта одам бор",
    "Тошкентдан хожаобод га битта одам бор",
    "Коргонтепага почта бор андижон га почта бор",
    "Коргонтепага почта бор",
    "Андижонга такси керак",
    "Тошкентдан андижон га пустой мошина керак",
    "Шархонга одам бор",
    "Бозга одам бор",
    "Срочныйга почта бор",
    "Тошкентда Ким бор",
    "Срочный йурадигон мошинага почта бор",
    "Почта бор алокага чикворилар",
    "Черняевкадан одам бор",
    "Чегарага одам бор",
    "Шарк Юлдуз га битта одам бор",
    "Уч тепага битта одам бор",
    "Тошкентдан нефтпрга одам бор",
    "Достлик га почта бор",
    "Тошкентдан булок боши га почта бор",
    "Тошкентдан булок боши га одам бор",
    "Жалакудук дан одам бор",
    "Булок боши дан одам бор",
    "Тошкентга мошина борми",
    "Тошкентдан булок боши га одам бор",
    "Тошкентдан ширмонбулокга одам бор",
    "Срочный га мошина керак",
    "Тошкентдан жалакудук га битта одам бор",
    "Тошкентдан хожаобод га битта одам бор",
    "Коргонтепага почта бор",
    "Андижонга такси керак",
    "Тошкентдан андижон га пустой мошина керак",
    "Шархонга одам бор",
    "Бозга одам бор",
    "Срочныйга почта бор",
    "Тошкентда Ким бор",
    "Срочный йурадигон мошинага почта бор",
    "Почта бор алокага чикворилар",
    "Черняевкадан одам бор",
    "Чегарага одам бор",
    "Шарк Юлдуз га битта одам бор",
    "Уч тепага битта одам бор",
    "Тошкентдан нефтпрга одам бор",
    "Достлик га почта бор",
    "Тошкентдан булок боши га почта бор",
    "Тошкентдан булок боши га одам бо",
    "Jalakuduk dan odam bor",
    "Bulok boshi dan odam bor",
    "Toshkentga moshina bormi",
    "Toshkentdan bulok boshi ga odam bor",
    "Toshkentdan shirmonbulokga odam bor",
    "Srochniy ga moshina kerak",
    "Toshkentdan jalakuduk ga bitta odam bor",
    "Toshkentdan xojaobod ga bitta odam bor",
    "Korgontepaga pochta bor andijon ga pochta bor",
    "Korgontepaga pochta bor",
    "Andijonga taksi kerak",
    "Toshkentdan andijon ga pustoy moshina kerak",
    "Sharxonga odam bor",
    "Bozga odam bor",
    "Srochniyga pochta bor",
    "Toshkentda Kim bor",
    "Srochniy yuradigon moshinaga pochta bor",
    "Pochta bor alokaga chikvorilar",
    "Chernyaevkadan odam bor",
    "Chegaraga odam bor",
    "Shark Yulduz ga bitta odam bor",
    "Uch tepaga bitta odam bor",
    "Toshkentdan neftprga odam bor",
    "Dostlik ga pochta bor",
    "Toshkentdan bulok boshi ga pochta bor",
    "Toshkentdan bulok boshi ga odam bor",
    "Jalakuduk dan odam bor",
    "Bulok boshi dan odam bor",
    "Toshkentga moshina bormi",
    "Toshkentdan bulok boshi ga odam bor",
    "Toshkentdan shirmonbulokga odam bor",
    "Srochniy ga moshina kerak",
    "Toshkentdan jalakuduk ga bitta odam bor",
    "Toshkentdan xojaobod ga bitta odam bor",
    "Korgontepaga pochta bor",
    "Andijonga taksi kerak",
    "Toshkentdan andijon ga pustoy moshina kerak",
    "Sharxonga odam bor",
    "Bozga odam bor",
    "Srochniyga pochta bor",
    "Toshkentda Kim bor",
    "Srochniy yuradigon moshinaga pochta bor",
    "Pochta bor alokaga chikvorilar",
    "Chernyaevkadan odam bor",
    "Chegaraga odam bor",
    "Shark Yulduz ga bitta odam bor",
    "Uch tepaga bitta odam bor",
    "Toshkentdan neftprga odam bor",
    "Dostlik ga pochta bor",
    "Toshkentdan bulok boshi ga pochta bor",
    "Toshkentdan bulok boshi ga odam bo",
    "yuradigon",
    "yuradigan",
    "Chernopkadan",
    "dastafka",
    "aeraportan",
    "yurishi kerak",
    "marhamatga",
    "powta bor",
    "moshina bormi",
    "Arab qishlog'",
    "xozrga",
    "hozrga",
    "xozirga",
    "hozirga",
    "kishi bor",
    "dona odam bor",
    "Gagaringa",
    "taksi bormi",
    "юрадигон",
    "юрадиган",
    "Чернопкадан",
    "дастафка",
    "аэрапортан",
    "юриши керак",
    "марҳаматга",
    "поwта бор",
    "мошина борми",
    "Араб қишлоғ",
    "хозрга",
    "ҳозрга",
    "хозирга",
    "ҳозирга",
    "киши бор",
    "дона одам бор",
    "Гагаринга",
    "такси борми",
    "moshina kerak",
    "мошина керак",
    # "kerak",
    "керак",
    "olish",
    "olvolish",
    "олиш",
    "олволиш",
]

DONT_TAKE = [
    "Хурматли",
    "📧 Xabar: ",
    "yuraman",
    "qo'shish",
    "odam kerak",
    "guruh",
    "оплата",
    "одам керак",
    "берилар",
    "berilar",
    "berila",
    "ЖЕНТРА",
    "JENTRA",
    "GENTRA",
    "гуруҳ",
    "kechirasiz",
    "кечирасиз",
    "qo'shishni o'chirish",
    "қўшишни ўчириш",
    "yozish uchun",
    "yozish",
    "reklama",
    "реклама",
    "ёзиш учун",
    "ёзиш",
    "юраман",
    "olaman",
    "оламан",
    "yuramz",
    "yuramiz",
    "reklama",
    "реклама",
    "toldik",
    "to'ldik",
    "toldk",
    "o'chirildi",
    "to'ldk",
    "foydalanuvchi",
    "kandisaner",
    "kam",
    "obketamiz",
    "opketamiz",
    "olamiz",
    "olamz",
    "оламз",
    "ketamiz",
    "Boylap",
    "Бойлап",
    "yuraman",
    "юраман",
    "Hudo holasa",
    "Ҳудо ҳоласа",
    "кетамиз",
    "Cobalt",
    "kobalt",
    "moshina",
    "юрамз",
    "юрамиз",
    "толдик",
    "тўлдик",
    "толдк",
    "тўлдк",
    "кандисанер",
    "кам",
    "обкетамиз",
    "опкетамиз",
    "оламиз",
    "Cобалт",
    "кобалт",
    "мошина",
]
