ALL_WORDS = [
    "odam bor",
    "ketaman",
    "pochta bot",
    "pocta bot",
    "po'chta bot",
    "po'cta bot",
    "siro'chni",
    "siro'chniy",
    "sirocniy",
    "sirocni",
    "sirocni",
    "srochniy",
    "sro'chniy",
    "sro'chni",
    "srochni",
    "ta odam bor",
    "bormoqchi",
    "bormoqci",
    "yangi buyurtma",
    "yangi buyurtma.",
    "yo'lovchi",
    "yo'lovci",
    "yolovchi",
    "yolovci",
    "Xabar",
    "xabar",
    "одам бор",
    "кетаман",
    "почта бот",
    "поcта бот",
    "пўчта бот",
    "пўcта бот",
    "сирўчни",
    "сирўчний",
    "сироcний",
    "сироcни",
    "сироcни",
    "суроcни",
    "срочний",
    "срўчний",
    "срўчни",
    "срочни",
    "та одам бор",
    "бормоқчи",
    "бормоқcи",
    "янги буюртма",
    "янги буюртма.",
    "йўловчи",
    "йўловcи",
    "ёловчи",
    "ёловcи",
    "Хабар",
    "хабар",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # # ===================================
    # "Tashkent",
    # "Toshkent",
    # "Тошкент",
    # "Андижон",
    # "Andijon",
    # "Такси керак",
    # "срочный",
    # "одам бор",
    # "йол кира канча",
    # "почта бор",
    # "срочный такси керак",
    # "алокага чикворилар",
    # "хожаобод",
    # "достлик",
    # "ширмонбулок",
    # "булок боши",
    # "Шарк Юлдуз",
    # "наиман",
    # "уч тепа",
    # "кулла",
    # "нефт пром",
    # "савхо",
    # "жалакудук",
    # "коргонтепа",
    # "корасув",
    # "Бештол",
    # "хонобод",
    # "зеленомост",
    # "олтин кол",
    # "шархон",
    # "асака",
    # "кува",
    # "баликчи",
    # "уч кахрамон",
    # "черняевка",
    # "Боз язйавон",
    # "перевал",
    # "Tashkent",
    # "Toshkent",
    # "Toshkent",
    # "Andijon",
    # "Andijon",
    # "Taksi kerak",
    # "srochniy",
    # "odam bor",
    # "yol kira kancha",
    # "pochta bor",
    # "srochniy taksi kerak",
    # "alokaga chikvorilar",
    # "xojaobod",
    # "dostlik",
    # "shirmonbulok",
    # "bulok boshi",
    # "Shark Yulduz",
    # "naiman",
    # "uch tepa",
    # "kulla",
    # "neft prom",
    # "savxo",
    # "jalakuduk",
    # "korgontepa",
    # "korasuv",
    # "Beshtol",
    # "xonobod",
    # "zelenomost",
    # "oltin kol",
    # "sharxon",
    # "asaka",
    # "kuva",
    # "balikchi",
    # "uch kaxramon",
    # "chernyayevka",
    # "Boz yazyavon",
    # "pereval",
]
DONT_TAKE = [
    # "yuramz",
    # "yuramiz",
    # "toldik",
    # "to'ldik",
    # "toldk",
    # "o'chirildi",
    # "to'ldk",
    # "foydalanuvchi",
    # "kandisaner",
    # "kam",
    # "obketamiz",
    # "opketamiz",
    # "olamiz",
    # "ketamiz",
    # "кетамиз",
    # "Cobalt",
    # "kobalt",
    # "moshina",
    # "юрамз",
    # "юрамиз",
    # "толдик",
    # "тўлдик",
    # "толдк",
    # "тўлдк",
    # "кандисанер",
    # "кам",
    # "обкетамиз",
    # "опкетамиз",
    # "оламиз",
    # "Cобалт",
    # "кобалт",
    # "мошина",
]