ALL_WORDS = [
    "Tashkent",
    "Toshkent",
    "Тошкент",
    "Андижон",
    "Andijon",
    "Такси керак",
    "срочный",
    "одам бор",
    "йол кира канча",
    "почта бор",
    "срочный такси керак",
    "алокага чикворилар",
    "хожаобод",
    "достлик",
    "ширмонбулок",
    "булок боши",
    "Шарк Юлдуз",
    "наиман",
    "уч тепа",
    "кулла",
    "нефт пром",
    "савхо",
    "жалакудук",
    "коргонтепа",
    "корасув",
    "Бештол",
    "хонобод",
    "зеленомост",
    "олтин кол",
    "шархон",
    "асака",
    "кува",
    "баликчи",
    "уч кахрамон",
    "черняевка",
    "Боз язйавон",
    "перевал",
    "Tashkent",
    "Toshkent",
    "Toshkent",
    "Andijon",
    "Andijon",
    "Taksi kerak",
    "srochniy",
    "odam bor",
    "yol kira kancha",
    "pochta bor",
    "srochniy taksi kerak",
    "alokaga chikvorilar",
    "xojaobod",
    "dostlik",
    "shirmonbulok",
    "bulok boshi",
    "Shark Yulduz",
    "naiman",
    "uch tepa",
    "kulla",
    "neft prom",
    "savxo",
    "jalakuduk",
    "korgontepa",
    "korasuv",
    "Beshtol",
    "xonobod",
    "zelenomost",
    "oltin kol",
    "sharxon",
    "asaka",
    "kuva",
    "balikchi",
    "uch kaxramon",
    "chernyayevka",
    "Boz yazyavon",
    "pereval",
]
